FROM debian:stable-20230411-slim

# Show emojis (?)
RUN apt-get update && \
    apt-get install -y fonts-noto-color-emoji libxft-dev libxrender-dev && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

# Specify Java dependencies to install with SDK-man
ARG JAVA_VERSION="22.3.r19-grl"
ARG MAVEN_VERSION="3.9.1"

# Miscelaneous
RUN apt-get update && \
	apt-get install -y zip unzip curl && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/*

# Install SDK-man
RUN curl -s "https://get.sdkman.io" | bash
RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh && \
    sdk install java $JAVA_VERSION && \
    sdk install maven $MAVEN_VERSION && \
    rm -rf /root/.sdkman/archives/* && \
    rm -rf /root/.sdkman/tmp/*"

# Specify actaul Java and Maven executables
ENV MAVEN_HOME="/root/.sdkman/candidates/maven/current"
ENV JAVA_HOME="/root/.sdkman/candidates/java/current"
ENV PATH="$MAVEN_HOME/bin:$JAVA_HOME/bin:$PATH"

# Import files
WORKDIR /code

COPY src ./src
COPY lib ./lib
COPY pom.xml .

# Compile solution in JAR
RUN mvn install:install-file -Dfile=./lib/FreePastry-2.1.jar -DgroupId=free-pastry -DartifactId=FreePastry -Dversion=2.1 -DgeneratePom=true -Dpackaging=jar
RUN mvn package

# Entry command
CMD [ "java", "-jar", "target/proof-of-work-p2p-1.0-SNAPSHOT-jar-with-dependencies.jar", "9001", "10.0.0.2" ]
